[package]
name = "graphics_test"
version = "0.1.0"
authors = ["CensoredUsername <cens.username@gmail.com>"]

[dependencies]
gfx = "0.*"
glutin = "0.*"
gfx_window_glutin = "0.*"
image = "0.*"
cgmath = "0.*"

[profile.release]
lto = true